"""Pydantic schemas for the Importação module."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

# ── Config ─────────────────────────────────────────────────────────────


class ImportConfigOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    # Categoria foi adicionada em 0132 (config era singleton, virou
    # uma row por categoria). Exposta pra o frontend confirmar qual
    # config está editando.
    categoria: str
    tempo_reposicao: int
    tempo_estoque: int


class ImportConfigPatch(BaseModel):
    tempo_reposicao: int | None = None
    tempo_estoque: int | None = None


# ── Cotação (parâmetros globais por categoria + patch por produto) ─────


class ImportCotacaoParamsOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    categoria: str
    taxa_cambio: Decimal
    frete_regular_pct: Decimal
    frete_swap_pct: Decimal
    frete_acessorios_pct: Decimal
    adicional: Decimal


class ImportCotacaoParamsPatch(BaseModel):
    taxa_cambio: Decimal | None = None
    frete_regular_pct: Decimal | None = None
    frete_swap_pct: Decimal | None = None
    frete_acessorios_pct: Decimal | None = None
    adicional: Decimal | None = None


class ImportProductCotacaoPatch(BaseModel):
    """Patch só dos 3 campos da aba Cotação. Endpoint separado pra
    deixar o autosave do ImportProductPatch (aba Importação/Mala) e
    o autosave da Cotação isolados."""
    valor_usd: Decimal | None = None
    valor_brl_realizado: Decimal | None = None
    frete_type: str | None = None


# ── Product ────────────────────────────────────────────────────────────


class ImportProductBase(BaseModel):
    # Categoria do selector top-level (mala/eletro/celular). Imutável após
    # criar — por isso fica fora do ImportProductPatch.
    categoria: str = "mala"
    fornecedor: str | None = None
    modelo_china: str | None = None
    cor_china: str | None = None
    fechamento: str | None = None
    tsa: int | None = None
    modelo_bling: str | None = None
    sku: str
    cor: str | None = None
    custo_bling: Decimal = Decimal("0")
    estoque_bling: int | None = None
    consumo_diario: Decimal | None = None
    maior_media_30d: Decimal | None = None
    obs: str | None = None
    # Cotação (aba Cotação do Celular, migration 0119). `valor_brl_previsto`
    # NÃO entra aqui — é calculado em tempo real no frontend.
    valor_usd: Decimal | None = None
    valor_brl_realizado: Decimal | None = None
    frete_type: str | None = "regular"


class ImportProductCreate(ImportProductBase):
    pass


class ImportProductPatch(BaseModel):
    fornecedor: str | None = None
    modelo_china: str | None = None
    cor_china: str | None = None
    fechamento: str | None = None
    tsa: int | None = None
    modelo_bling: str | None = None
    sku: str | None = None
    cor: str | None = None
    custo_bling: Decimal | None = None
    estoque_bling: int | None = None
    consumo_diario: Decimal | None = None
    maior_media_30d: Decimal | None = None
    obs: str | None = None


class ImportProductOut(ImportProductBase):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    # Computed fields appended by the router (not stored).
    memoria_consumo: Decimal | None = None
    reposicao_estoque: int | None = None
    saldo_reposicao: int | None = None
    # "media do custo" — computed no GET /products como
    # Σ(qty × custoBRL_lote) / Σ(qty) dos ImportLoteItem do produto.
    # NÃO existe no DB (dropada na migration 0123). Endpoints que
    # respondem 1 produto (create/patch) devolvem None.
    custo_realizado: Decimal | None = None
    # Generated by `generate_mala_name(modelo_bling, sku, cor)` — kept on
    # the response so the frontend grid can show the canonical display
    # name without duplicating the rule. Always recomputed (never stored).
    nome_gerado: str = ""
    # Bling sync state — see model for state machine.
    bling_sync_status: str | None = None
    bling_sync_marked_at: datetime | None = None
    bling_product_id: int | None = None
    bling_sync_error: str | None = None
    bling_sync_attempted_at: datetime | None = None
    bling_sync_done_at: datetime | None = None
    # Quantities keyed by lote_id (str) → quantity. The frontend uses
    # this to render dynamic per-lote columns without needing a second
    # request per row.
    lote_quantidades: dict[str, int] = {}
    # Paralelo a lote_quantidades, só pra Celular: valor unitário em
    # USD do produto NAQUELE lote. Ausente / valor null → operador
    # ainda não preencheu.
    lote_valores_usd: dict[str, Decimal | None] = {}
    # Paralelo, só pra Celular: custo BRL manual unitário do produto
    # NAQUELE lote. Usado quando o lote não tem taxa/frete e a fórmula
    # valor_usd × taxa × (1+frete) + adicional não se aplica (migration
    # 0128). Ausente / null → operador ainda não preencheu.
    lote_custos_manuais: dict[str, Decimal | None] = {}
    # Migration 0138 (Celular). Override por (produto, lote) do SKU
    # destino pra entrada de estoque no Bling. Frontend usa pra mostrar
    # o valor atual do dropdown; null = comportamento default (vai pro
    # SKU do próprio ImportProduct). Paralelo a `lote_item_ids` — o
    # PATCH precisa do item_id.
    lote_target_skus: dict[str, str | None] = {}
    lote_item_ids: dict[str, str] = {}
    created_at: datetime
    updated_at: datetime


# ── Lote ───────────────────────────────────────────────────────────────


class ImportLoteCreate(BaseModel):
    nome: str
    abertura: date
    categoria: str = "mala"
    transportadora: str | None = None
    obs: str | None = None
    # Pra celular, se não passar, backend prefilla com ImportCotacaoParams.
    taxa: Decimal | None = None
    frete_pct: Decimal | None = None
    adicional: Decimal | None = None


class ImportLotePatch(BaseModel):
    nome: str | None = None
    abertura: date | None = None
    fechamento: date | None = None
    realizado: Decimal | None = None
    transportadora: str | None = None
    obs: str | None = None
    # Override do previsto computed. Pra zerar de volta pro computed,
    # mande explicitamente null (model_dump exclude_unset=True respeita).
    previsto_manual: Decimal | None = None
    # Params da fórmula do custo BRL por lote (Celular, migration 0122).
    taxa: Decimal | None = None
    frete_pct: Decimal | None = None
    adicional: Decimal | None = None
    # Nº da DI (migration 0214) — editável direto no header do lote.
    di_numero: str | None = None


class ImportLoteOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    categoria: str = "mala"
    nome: str
    abertura: date
    fechamento: date | None = None
    realizado: Decimal
    transportadora: str | None = None
    obs: str | None = None
    # Override do previsto (quando NULL, _enrich_lote calcula via SUM).
    # Frontend usa pra saber se mostra o valor como editável (manual) ou
    # como label (computed).
    previsto_manual: Decimal | None = None
    # Params do custo BRL por lote (Celular). Em Mala ficam NULL.
    taxa: Decimal | None = None
    frete_pct: Decimal | None = None
    adicional: Decimal | None = None
    # Computed by the router:
    previsto: Decimal = Decimal("0")
    saldo: Decimal = Decimal("0")
    prazo: int | None = None  # days between abertura and fechamento
    is_aberto: bool = True
    # Migration 0138 (Celular). Agregado da entrada de estoque no Bling
    # disparada ao fechar o lote. Frontend mostra um badge no header
    # do lote. NULL = nunca rodou (lote aberto); preenchido = job rodou
    # e gerou esses contadores. Usado só pra display.
    bling_stock_total: int = 0
    bling_stock_sent: int = 0
    bling_stock_skipped: int = 0
    bling_stock_errors: int = 0
    # Simulação + DI (migration 0214). Blobs NÃO vão na listagem — só
    # os derivados booleanos; PDFs servidos por endpoints dedicados.
    di_numero: str | None = None
    tem_simulacao_pdf: bool = False
    tem_di_pdf: bool = False
    di_pagamento: dict | None = None


class DiPagamentoIn(BaseModel):
    """Lançamento do pagamento da DI no Bling (contas a pagar).

    O valor total é dividido em N parcelas iguais (resto de centavos na
    última), vencimentos espaçados por período a partir do 1º vencimento.
    """
    valor_total: Decimal = Field(gt=0)
    parcelas: int = Field(ge=1, le=60)
    periodo: Literal["mensal", "semanal"] = "mensal"
    primeiro_vencimento: date


# ── LoteItem (quantity per SKU per lote) ───────────────────────────────


class ImportLoteItemUpsert(BaseModel):
    product_id: UUID
    quantidade: int
    # Pra celular: valor unitário em USD POR LOTE. Quando None, item
    # fica sem valor próprio (cai pra produto.valor_usd no frontend).
    valor_usd: Decimal | None = None


class ImportLoteItemPatch(BaseModel):
    """Patch de atributos editáveis do item.

    - `pago`: toggle da aba Frete.
    - `custo_manual`: aba Importação Celular — custo BRL unitário
      digitado pelo operador quando o lote não tem taxa/frete (a
      fórmula valor_usd × taxa × (1+frete) + adicional não se aplica).
      `None` explícito limpa.
    - `bling_stock_target_sku`: aba Importação Celular — SKU destino
      override pra entrada de estoque no Bling ao fechar lote.
      `None` explícito limpa (volta a usar o SKU do ImportProduct).
    """
    pago: bool | None = None
    custo_manual: Decimal | None = None
    bling_stock_target_sku: str | None = None


# ── Frete (aba Frete do Celular, etapa 4) ─────────────────────────────


class ImportFreteRow(BaseModel):
    """Linha agregada da aba Frete. Mistura:
      * items de lotes (uma linha por lote_item — modelo, qtd, valor)
      * ajustes manuais (linha de ImportResumo com transportadora set,
        modelo/qtd/valor todos None — só saldo)
    `id` é o id da fonte (lote_item ou resumo); `kind` distingue."""
    kind: str  # 'item' | 'ajuste'
    id: UUID
    transportadora: str | None = None
    lote_id: UUID | None = None
    lote_nome: str | None = None
    abertura: date | None = None
    fechamento: date | None = None
    modelo_bling: str | None = None
    sku: str | None = None
    quantidade: int | None = None
    valor_unit: Decimal | None = None
    total: Decimal | None = None
    frete_pct: Decimal | None = None
    saldo: Decimal | None = None
    pago: bool = False
    obs: str | None = None


class ImportFreteList(BaseModel):
    rows: list[ImportFreteRow]
    transportadoras: list[str]  # distinct, pra dropdown
    # Cards de resumo no topo da aba.
    total_a_entregar: Decimal = Decimal("0")  # lotes sem fechamento
    saldo_a_pagar: Decimal = Decimal("0")     # lotes fechados, !pago


class ImportFreteAjusteCreate(BaseModel):
    """Body do POST /lote_ajuste — cria uma row em import_resumo com
    `transportadora` setada (linha avulsa que aparece na aba Frete)."""
    transportadora: str
    abertura: date
    saldo: Decimal
    obs: str | None = None
    # Identificador opcional do ajuste (ex: "AJ-001"). Espelha o
    # `lote_nome` exibido na aba Frete; patchable via PATCH /resumo.
    lote_nome: str | None = None
    categoria: str = "celular"


# ── Resumo ─────────────────────────────────────────────────────────────


class ImportResumoCreate(BaseModel):
    data: date
    lote_id: UUID | None = None
    lote_nome: str | None = None
    saldo: Decimal
    obs: str | None = None
    categoria: str = "mala"
    transportadora: str | None = None


class ImportResumoPatch(BaseModel):
    """Edição de uma linha do Resumo. Originalmente só `obs`; estendido
    pra cobrir ajustes manuais da aba Frete (transportadora, data,
    saldo, lote_nome). Esvaziar `transportadora` removeria a row da aba
    Frete — bloqueado no router."""
    transportadora: str | None = None
    data: date | None = None
    saldo: Decimal | None = None
    lote_nome: str | None = None
    obs: str | None = None


class ImportResumoOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    categoria: str = "mala"
    data: date
    lote_id: UUID | None = None
    lote_nome: str | None = None
    saldo: Decimal
    obs: str | None = None
    transportadora: str | None = None
    # ImportResumo is intentionally append-only (no TimestampMixin)
    # so the model doesn't expose created_at — keep the schema in sync
    # or the GET endpoint 500s on Pydantic validation.


class ImportResumoList(BaseModel):
    items: list[ImportResumoOut]
    total: Decimal


# ── Cotação ────────────────────────────────────────────────────────────


class CotacaoFabricanteOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    nome: str
    obs1: str | None = None
    obs2: str | None = None
    obs3: str | None = None
    obs4: str | None = None
    ordem: int


class CotacaoFabricantePatch(BaseModel):
    nome: str | None = None
    obs1: str | None = None
    obs2: str | None = None
    obs3: str | None = None
    obs4: str | None = None
    ordem: int | None = None


class CotacaoProdutoOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    nome: str
    ordem: int


class CotacaoProdutoPatch(BaseModel):
    nome: str | None = None
    ordem: int | None = None


class CotacaoValorOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    fabricante_id: UUID
    produto_id: UUID
    capacidade: str | None = None
    valor_real: Decimal | None = None
    valor_usd: Decimal | None = None


class CotacaoValorUpsert(BaseModel):
    fabricante_id: UUID
    produto_id: UUID
    capacidade: str | None = None
    valor_real: Decimal | None = None
    valor_usd: Decimal | None = None


class CotacaoGridOut(BaseModel):
    """Grid completo da aba Cotação. Frontend monta o lookup
    `valores[produto_id][fabricante_id] = {...}` a partir desta lista."""
    fabricantes: list[CotacaoFabricanteOut]
    produtos: list[CotacaoProdutoOut]
    valores: list[CotacaoValorOut]


# ── Kit (aba Kit — matriz produto × variação) ────────────────────────


class ImportKitVariationOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    code: str
    label: str
    ordem: int
    highlight: bool
    obs: str | None = None


class ImportKitVariationCreate(BaseModel):
    """POST /importacao/kit/variations body. `categoria` ∈ (mala, celular);
    `code` é validado conforme a categoria pelo router."""
    categoria: str
    code: str
    label: str


class ImportKitBaseOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    modelo_bling: str | None = None
    sku_base: str
    cor: str | None = None
    ordem: int


class ImportKitMarkOut(BaseModel):
    """Célula marcada. Inclui `id` (pra resync), estado do sync com
    o Bling (fase 2) e estado do sync com pricing_products (fase 3).
    Frontend usa `${base_id}::${variation_id}` como chave do lookup."""
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    base_id: UUID
    variation_id: UUID
    bling_product_id: int | None = None
    bling_sync_status: str | None = None  # 'pending' | 'sent' | 'error'
    bling_sync_error: str | None = None
    bling_sync_attempted_at: datetime | None = None
    bling_sync_done_at: datetime | None = None
    pricing_product_id: UUID | None = None
    pricing_sync_status: str | None = None  # 'pending' | 'sent' | 'error'
    pricing_sync_error: str | None = None
    pricing_sync_done_at: datetime | None = None


class ImportKitGridOut(BaseModel):
    variations: list[ImportKitVariationOut]
    bases: list[ImportKitBaseOut]
    marks: list[ImportKitMarkOut]


class ImportKitMarkToggle(BaseModel):
    base_id: UUID
    variation_id: UUID
    marked: bool
